In [1]:
#Mount google drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
import pandas as pd   #pd is an alias for pandas

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Teaching/BDA6140/GitHub/BDA6140-Spring-2026/Data/CompactSUV.csv")
df

,Make,Model,Overall Score,Recommended,Owner Satisfaction,Overall Miles Per Gallon,Acceleration (0-60) Sec
0,Subaru,Forester,84,Yes,+,26,8.7
1,Honda,CRV,83,Yes,++,27,8.6
2,Toyota,Rav4,81,Yes,++,24,9.3
3,Nissan,Rogue,73,Yes,+,24,9.5
4,Mazda,CX-5,71,Yes,++,24,8.6
5,Kia,Sportage,71,Yes,+,23,9.6
6,Ford,Escape,69,Yes,0,23,10.1
7,Volkswagen,Tiguan Limited,67,No,0,21,8.5
8,Volkswagen,Tiguan,65,No,+,25,10.3
9,Mitsubishi,Outlander,63,No,0,24,10.0
10,Chevrolet,Equinox,63,No,0,31,10.1
11,Hyundai,Tuscon,57,No,0,26,8.4
12,GMC,Terrain,57,No,0,22,7.2
13,Jeep,Cherokee,55,No,-,22,10.9
14,Jeep,Compass,50,No,0,24,9.8

In [5]:
df2 = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Teaching/BDA6140/GitHub/BDA6140-Spring-2026/Data/dataset.xlsx", sheet_name = "CarBuyers")

df2

   CustomerID               Name         City  Age Sex
0         981         Jane Smith       Boston   56   F
1         459          Tom Perez    Worcester   49   M
2         272     Kate Greenbaum    Worcester   65   F
3         832  Alisha Washington  Springfield   42   F
4         553         Ken Castro       Boston   55   M
5         776        Leonard Liu  Springfield   57   M
6         379       Sam Thurston    Worcester   40   M
7         742      Sydney Benoit       Boston   67   F